name: Deploy OCR Function App

on:
  push:
    branches:
      - backend-ocr
    paths:
      - 'ocr/**'
      - '.github/workflows/deploy-ocr-function.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'qadam-ocr'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'ocr'
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Check if publish profile is set'
      run: |
        if [ -z "${{ secrets.AZURE_OCR_FUNCTIONAPP_PUBLISH_PROFILE }}" ]; then
          echo "❌ ERROR: AZURE_OCR_FUNCTIONAPP_PUBLISH_PROFILE secret is not set!"
          echo "📋 Please follow these steps:"
          echo "1. Create Azure Function App 'qadam-ocr'"
          echo "2. Download publish profile from Azure Portal"
          echo "3. Add it as GitHub secret: AZURE_OCR_FUNCTIONAPP_PUBLISH_PROFILE"
          echo "4. See ocr/AZURE_SETUP.md for detailed instructions"
          exit 1
        fi
        echo "✅ Publish profile found"
    
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Deploy to Azure Functions using CLI'
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        zip -r ../deploy.zip .
        cd ..
        az functionapp deployment source config-zip \
          --resource-group qadam_ocr \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --src deploy.zip \
          --build-remote true

    - name: 'Deployment Summary'
      run: |
        echo "✅ OCR Function App deployed successfully!"
        echo "📦 Function App: ${{ env.AZURE_FUNCTIONAPP_NAME }}"
        echo "🔗 URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
